connector.name=cassandra
cassandra.contact-points=cassandra
cassandra.native-protocol-port=9042
cassandra.load-policy.use-dc-aware=true
cassandra.load-policy.dc-aware.local-dc=datacenter1
cassandra.username=cassandra
cassandra.password=cassandra
cassandra.protocol-version=V5
cassandra.allow-drop-table=true
cassandra.client.read-timeout=30000ms
cassandra.client.connect-timeout=10000ms
