spark.master                     spark://spark:7077

spark.driver.extraJavaOptions     -Dcassandra.releaseVersion=5.0.6 -Dcassandra.analytics.bridges.sstable_format=bti
spark.executor.extraJavaOptions   -Dcassandra.releaseVersion=5.0.6 -Dcassandra.analytics.bridges.sstable_format=bti

# Ivy cache configuration for --packages
spark.jars.ivy                    /opt/spark/work-dir/.ivy2

spark.sql.warehouse.dir /tmp/spark-warehouse
javax.jdo.option.ConnectionURL jdbc:derby:;databaseName=/tmp/metastore_db;create=true

# cassandra spark bulk writer needs KryoSerializer
spark.serializer    org.apache.spark.serializer.KryoSerializer