package com.thelastpickle.htap.backend.vector;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * Every expected weight below was generated by running the Python {@code local_embedding} this
 * class replaces, so the comparison is against the function that wrote the vectors now in {@code
 * demo.drone_text_embeddings}. A query embedded here has to hash a token to the dimension that
 * function used, or the stored rows all rank as noise.
 */
class LocalEmbedderTest {

    private final LocalEmbedder embedder = new LocalEmbedder();

    private record Weight(int dimension, double value) {}

    @Test
    void oneTokenLandsInTheDimensionItsDigestNames() {
        assertWeights(embedder.embed("drone"), new Weight(144, -1.0));
    }

    @Test
    void caseIsFoldedBeforeHashing() {
        assertArrayEquals(embedder.embed("drone"), embedder.embed("DRONE"));
        assertArrayEquals(embedder.embed("drone"), embedder.embed("Drone"));
    }

    /** Eight dimensions for nine kept tokens, because "the" occurs twice and doubles its weight. */
    @Test
    void aSentenceLandsWhereThePythonPutIt() {
        float[] vector =
                embedder.embed("The drone climbed over the airport perimeter, then held.");

        assertWeights(
                vector,
                new Weight(144, -0.301511344578),
                new Weight(188, -0.301511344578),
                new Weight(426, -0.301511344578),
                new Weight(876, -0.603022689156),
                new Weight(1108, 0.301511344578),
                new Weight(1334, -0.301511344578),
                new Weight(1500, -0.301511344578),
                new Weight(1505, -0.301511344578));
    }

    @Test
    void punctuationAndDigitsSplitAsTheTokenPatternSays() {
        assertWeights(
                embedder.embed("quick brown fox jumps over the lazy dog"),
                new Weight(33, 0.353553390593),
                new Weight(276, -0.353553390593),
                new Weight(449, -0.353553390593),
                new Weight(507, -0.353553390593),
                new Weight(729, -0.353553390593),
                new Weight(876, -0.353553390593),
                new Weight(1008, 0.353553390593),
                new Weight(1334, -0.353553390593));
    }

    @Test
    void oneTokenRepeatedNormalisesBackToUnitLength() {
        assertWeights(embedder.embed("drone drone drone"), new Weight(144, -1.0));
    }

    @Test
    void tokensShorterThanThreeCharactersAreDropped() {
        assertArrayEquals(embedder.embed("drone"), embedder.embed("a bc drone!"));
    }

    @Test
    void aTextWithNothingToHashIsTheProbeVector() {
        assertArrayEquals(LocalEmbedder.probe(), embedder.embed(""));
        assertArrayEquals(LocalEmbedder.probe(), embedder.embed("a bc 12 !!"));
    }

    @Test
    void theProbeVectorIsItselfOfUnitLength() {
        float[] probe = LocalEmbedder.probe();

        assertEquals(LocalEmbedder.DIMENSIONS, probe.length);
        assertEquals(1.0, dot(probe, probe), 1e-9);
    }

    /** The claim the demo rests on: shared vocabulary is nearer than none, whatever the wording. */
    @Test
    void sharedVocabularyScoresAboveNone() {
        float[] query = embedder.embed("restricted airspace near the airport");
        float[] related = embedder.embed("airport airspace restricted");
        float[] unrelated = embedder.embed("battery temperature nominal cruising");

        assertEquals(0.774596669241, dot(query, related), 1e-6);
        assertEquals(0.0, dot(query, unrelated), 1e-6);
        assertTrue(dot(query, related) > dot(query, unrelated));
    }

    @Test
    void theEmbedderNamesItselfAsTheExplorePageReportsIt() {
        assertEquals("local", embedder.kind());
    }

    private static double dot(float[] a, float[] b) {
        double product = 0.0;
        for (int i = 0; i < a.length; i++) {
            product += (double) a[i] * b[i];
        }
        return product;
    }

    private static void assertWeights(float[] vector, Weight... expected) {
        assertEquals(LocalEmbedder.DIMENSIONS, vector.length);
        assertEquals(1.0, dot(vector, vector), 1e-6, "not a unit vector");

        List<Integer> occupied = new ArrayList<>();
        for (int i = 0; i < vector.length; i++) {
            if (vector[i] != 0.0f) {
                occupied.add(i);
            }
        }
        assertEquals(List.of(expected).stream().map(Weight::dimension).toList(), occupied);
        for (Weight weight : expected) {
            assertEquals(weight.value(), vector[weight.dimension()], 1e-6);
        }
    }
}
